import {
  facebook,
  instagram,
  shieldTick,
  support,
  truckFast,
  twitter,
} from "../assets/icons";
import {
  bigShoe1,
  bigShoe2,
  bigShoe3,
  customer1,
  customer2,
  JD,
  jameson,
  redLabel,
  blackLabel,
  thumbnailShoe1,
  thumbnailShoe2,
  thumbnailShoe3,
} from "../assets/images";

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "#about-us", label: "About Us" },
  { href: "/products", label: "Products" },
  { href: "#contact-us", label: "Contact Us" },
];

export const shoes = [
  { id: 1, thumbnail: thumbnailShoe1, bigShoe: bigShoe1 },
  { id: 2, thumbnail: thumbnailShoe2, bigShoe: bigShoe2 },
  { id: 3, thumbnail: thumbnailShoe3, bigShoe: bigShoe3 },
];

export const statistics = [
  { value: "300+", label: "Brands" },
  { value: "20k+", label: "Engagements" },
  { value: "2k+", label: "Customers" },
];

export const products = [
  {
    id: 1,
    imgURL: JD,
    name: "Old Oak Whiskey",
    price: 4350,
    category: "Spirits",
    subcategory: "Whiskey",
    filter: "new",
    popular: true,
    specialOffer: false,
  },
  {
    id: 2,
    imgURL: jameson,
    name: "Velvet Red Wine",
    price: 2890,
    category: "Wines",
    subcategory: "Red Wine",
    filter: "best sellers",
    popular: true,
    specialOffer: true,
  },
  {
    id: 3,
    imgURL: redLabel,
    name: "Bavarian Lager",
    price: 3750,
    category: "Beers, Infusions & Sake",
    subcategory: "Beers",
    filter: "popular",
    popular: false,
    specialOffer: true,
  },
  {
    id: 4,
    imgURL: blackLabel,
    name: "Classic Margarita",
    price: 4970,
    category: "Cocktails",
    subcategory: null,
    filter: "new",
    specialOffer: false,
  },
  {
    id: 5,
    imgURL: JD,
    name: "Crystal Stemware Set",
    price: 4560,
    category: "Glassware",
    subcategory: "Glassware",
    filter: "best sellers",
    specialOffer: false,
    popular: true,
  },
  {
    id: 6,
    imgURL: jameson,
    name: "Fever Tree Tonic",
    price: 3150,
    category: "Non-Alcoholic Drinks",
    subcategory: "Mixers",
    filter: "popular",
    specialOffer: false,
    popular: false,
  },
  {
    id: 7,
    imgURL: redLabel,
    name: "Russian Vodka",
    price: 4920,
    category: "Spirits",
    subcategory: "Vodka",
    filter: "new",
    specialOffer: true,
    popular: false,
  },
  {
    id: 8,
    imgURL: blackLabel,
    name: "Chardonnay Reserve",
    price: 2500,
    category: "Wines",
    subcategory: "White Wine",
    filter: "best sellers",
    specialOffer: false,
    popular: true,
  },
  {
    id: 9,
    imgURL: JD,
    name: "Golden Cider",
    price: 4190,
    category: "Beers, Infusions & Sake",
    subcategory: "Ciders",
    filter: "popular",
    specialOffer: true,
    popular: false,
  },
  {
    id: 10,
    imgURL: jameson,
    name: "Minty Mojito",
    price: 3800,
    category: "Cocktails",
    subcategory: null,
    filter: "new",
    specialOffer: false,
    popular: true,
  },
  {
    id: 11,
    imgURL: redLabel,
    name: "Premium Brandy",
    price: 4300,
    category: "Spirits",
    subcategory: "Cognac & Brandy",
    filter: "best sellers",
    specialOffer: false,
    popular: false,
  },
  {
    id: 12,
    imgURL: blackLabel,
    name: "London Dry Gin",
    price: 3100,
    category: "Spirits",
    popular: true,
    subcategory: "Gin",
    filter: "popular",
    specialOffer: true,
  },
  {
    id: 13,
    imgURL: JD,
    name: "Sparkling Rosé",
    price: 3600,
    category: "Wines",
    subcategory: "Champagne & Sparkling Wine",
    filter: "new",
    specialOffer: false,
    popular: false,
  },
  {
    id: 14,
    imgURL: jameson,
    name: "Classic Highball Glass Set",
    price: 4700,
    category: "Glassware",
    subcategory: "Bar Accessories",
    specialOffer: false,
    filter: "best sellers",
    popular: false,
  },
  {
    id: 15,
    imgURL: redLabel,
    name: "Soft Strawberry Cider",
    price: 5200,
    category: "Beers, Infusions & Sake",
    subcategory: "Ciders",
    filter: "popular",
    specialOffer: true,
    popular: true,
  },
  {
    id: 16,
    imgURL: blackLabel,
    name: "Sierra Tequila",
    price: 2100,
    category: "Spirits",
    subcategory: "Tequila",
    filter: "new",
    specialOffer: false,
    popular: true,
  },
  {
    id: 17,
    imgURL: JD,
    name: "Caribbean Dark Rum",
    price: 4050,
    category: "Spirits",
    subcategory: "Rum",
    filter: "best sellers",
    specialOffer: false,
    popular: false,
  },
  {
    id: 18,
    imgURL: jameson,
    name: "Rosé Delight",
    price: 2750,
    category: "Wines",
    subcategory: "Rose Wine",
    filter: "popular",
    specialOffer: true,
    popular: true,
  },
  {
    id: 19,
    imgURL: redLabel,
    name: "Japanese Sake",
    price: 4600,
    category: "Beers, Infusions & Sake",
    subcategory: "Sake",
    filter: "new",
    specialOffer: false,
    popular: false,
  },
  {
    id: 20,
    imgURL: blackLabel,
    name: "Vintage Cognac",
    price: 3400,
    category: "Spirits",
    subcategory: "Cognac & Brandy",
    filter: "best sellers",
    specialOffer: false,
    popular: false,
  },
  {
    id: 21,
    imgURL: JD,
    name: "Gin Tonic Mixer Pack",
    price: 4900,
    category: "Non-Alcoholic Drinks",
    subcategory: "Mixers",
    filter: "popular",
    specialOffer: true,
    popular: true,
  },
  {
    id: 22,
    imgURL: jameson,
    name: "French Brut Champagne",
    price: 2800,
    category: "Wines",
    subcategory: "Champagne & Sparkling Wine",
    filter: "new",
    specialOffer: false,
    popular: true,
  },
  {
    id: 23,
    imgURL: redLabel,
    name: "Hops Lager Beer",
    price: 3300,
    category: "Beers, Infusions & Sake",
    subcategory: "Beers",
    filter: "best sellers",
    specialOffer: true,
    popular: false,
  },
  {
    id: 24,
    imgURL: blackLabel,
    name: "Moscow Mule Cocktail",
    price: 5200,
    category: "Cocktails",
    subcategory: null,
    filter: "popular",
    specialOffer: false,
  },
  {
    id: 25,
    imgURL: JD,
    name: "Stemless Wine Glass Set",
    price: 3990,
    category: "Glassware",
    subcategory: "Glassware",
    filter: "new",
    popular: true,
    specialOffer: true,
  },
  {
    id: 26,
    imgURL: jameson,
    name: "Virgin Mojito",
    price: 3190,
    category: "Non-Alcoholic Drinks",
    subcategory: "Non-Alcoholic Spirits",
    filter: "best sellers",
    specialOffer: false,
    popular: false,
  },
  {
    id: 27,
    imgURL: redLabel,
    name: "Maple Bourbon",
    price: 3050,
    category: "Spirits",
    subcategory: "Whiskey",
    filter: "popular",
    specialOffer: true,
    popular: true,
  },
  {
    id: 28,
    imgURL: blackLabel,
    name: "Pinot Noir",
    price: 4490,
    category: "Wines",
    subcategory: "Red Wine",
    filter: "new",
    specialOffer: false,
    popular: false,
  },
  {
    id: 29,
    imgURL: JD,
    name: "Premium Pilsner",
    price: 4890,
    category: "Beers, Infusions & Sake",
    subcategory: "Beers",
    specialOffer: true,
    filter: "best sellers",
    popular: true,
  },
  {
    id: 30,
    imgURL: jameson,
    name: "Triple Sec Liqueur",
    price: 2100,
    category: "Spirits",
    subcategory: "Liqueurs",
    specialOffer: false,
    filter: "popular",
    popular: false,
  },
  {
    id: 31,
    imgURL: redLabel,
    name: "Merlot Red Wine",
    price: 4550,
    category: "Wines",
    subcategory: "Red Wine",
    filter: "new",
    specialOffer: false,
    popular: false,
  },
  {
    id: 32,
    imgURL: blackLabel,
    name: "Tequila Sunrise",
    price: 3770,
    category: "Cocktails",
    popular: true,
    subcategory: null,
    filter: "best sellers",
    specialOffer: true,
  },
  {
    id: 33,
    imgURL: JD,
    name: "French Chablis",
    price: 5100,
    category: "Wines",
    subcategory: "White Wine",
    filter: "popular",
    specialOffer: false,
    popular: false,
  },
  {
    id: 34,
    imgURL: jameson,
    name: "Amaretto Liqueur",
    price: 3300,
    category: "Spirits",
    subcategory: "Liqueurs",
    filter: "new",
    specialOffer: true,
    popular: true,
  },
  {
    id: 35,
    imgURL: redLabel,
    name: "American Pale Ale",
    price: 3150,
    category: "Beers, Infusions & Sake",
    subcategory: "Beers",
    specialOffer: true,
    filter: "best sellers",
    popular: false,
  },
  {
    id: 36,
    imgURL: blackLabel,
    name: "Elderflower Tonic",
    price: 4900,
    category: "Non-Alcoholic Drinks",
    subcategory: "Mixers",
    filter: "popular",
    popular: true,
    specialOffer: false,
  },
  {
    id: 37,
    imgURL: JD,
    name: "Cask Bourbon",
    price: 3290,
    category: "Spirits",
    subcategory: "Whiskey",
    filter: "new",
    specialOffer: false,
    popular: true,
  },
  {
    id: 38,
    imgURL: jameson,
    name: "Champagne Flutes",
    price: 2750,
    category: "Glassware",
    subcategory: "Glassware",
    specialOffer: true,
    filter: "best sellers",
    popular: false,
  },
  {
    id: 39,
    imgURL: redLabel,
    name: "Peach Bellini",
    price: 4850,
    category: "Cocktails",
    subcategory: null,
    filter: "popular",
    specialOffer: false,
    popular: true,
  },
  {
    id: 40,
    imgURL: blackLabel,
    name: "Mexican Lager",
    price: 2400,
    category: "Beers, Infusions & Sake",
    subcategory: "Beers",
    filter: "new",
    specialOffer: false,
    popular: false,
  },
  {
    id: 41,
    imgURL: JD,
    name: "Blood Orange Gin",
    price: 3800,
    category: "Spirits",
    subcategory: "Gin",
    filter: "best sellers",
    specialOffer: true,
    popular: false,
  },
  {
    id: 42,
    imgURL: jameson,
    name: "Cabernet Sauvignon",
    price: 3350,
    category: "Wines",
    subcategory: "Red Wine",
    filter: "popular",
    popular: true,
    specialOffer: false,
  },
  {
    id: 43,
    imgURL: redLabel,
    name: "Sparkling Sangria",
    price: 2990,
    category: "Cocktails",
    subcategory: null,
    specialOffer: true,
    filter: "new",
    popular: false,
  },
  {
    id: 44,
    imgURL: blackLabel,
    name: "Single Malt Scotch",
    price: 4890,
    category: "premium collections",
    subcategory: "Whiskey",
    filter: "best sellers",
    specialOffer: false,
    popular: true,
  },
  {
    id: 45,
    imgURL: JD,
    name: "Tropical Piña Colada",
    price: 2450,
    category: "Cocktails",
    subcategory: null,
    specialOffer: true,
    filter: "popular",
    popular: false,
  },
  {
    id: 46,
    imgURL: jameson,
    name: "Barista Espresso",
    price: 2900,
    category: "Non-Alcoholic Drinks",
    subcategory: "Non-Alcoholic Spirits",
    filter: "new",
    specialOffer: false,
    popular: true,
  },
  {
    id: 47,
    imgURL: redLabel,
    name: "Old Vine Zinfandel",
    price: 4490,
    category: "Wines",
    subcategory: "Red Wine",
    filter: "best sellers",
    specialOffer: false,
    popular: false,
  },
  {
    id: 48,
    imgURL: blackLabel,
    name: "Imported IPA",
    price: 3900,
    category: "Beers, Infusions & Sake",
    subcategory: "Beers",
    filter: "popular",
    specialOffer: false,
    popular: false,
  },
  {
    id: 49,
    imgURL: JD,
    name: "Tahitian Rum",
    price: 4120,
    category: "Spirits",
    specialOffer: true,
    subcategory: "Rum",
    filter: "new",
    popular: true,
  },
  {
    id: 50,
    imgURL: jameson,
    name: "Irish Coffee Liqueur",
    price: 2780,
    category: "Spirits",
    subcategory: "Liqueurs",
    filter: "best sellers",
    specialOffer: false,
    popular: true,
  },
];

export const reviews = [
  {
    imgURL: customer1,
    customerName: "Morich Brown",
    rating: 4.5,
    feedback:
      "The attention to detail and the quality of the product exceeded my expectations. Highly recommended!",
  },
  {
    imgURL: customer2,
    customerName: "Lota Mongeskar",
    rating: 4.5,
    feedback:
      "The product not only met but exceeded my expectations. I'll definitely be a returning customer!",
  },
  {
    imgURL: customer1,
    customerName: "Oriel Brown",
    rating: 4.5,
    feedback:
      "The attention to detail and the quality of the product exceeded my expectations. Highly recommended!",
  },
  {
    imgURL: customer2,
    customerName: "Walter Mongera",
    rating: 4.5,
    feedback:
      "The product not only met but exceeded my expectations. I'll definitely be a returning customer!",
  },
  {
    imgURL: customer1,
    customerName: "Wee wacha bana",
    rating: 4.5,
    feedback:
      "The attention to detail and the quality of the product exceeded my expectations. Highly recommended!",
  },
  {
    imgURL: customer2,
    customerName: "yoow bettr",
    rating: 4.5,
    feedback:
      "The product not only met but exceeded my expectations. I'll definitely be a returning customer!",
  },
  {
    imgURL: customer1,
    customerName: "Test !",
    rating: 4.5,
    feedback:
      "The attention to detail and the quality of the product exceeded my expectations. Highly recommended!",
  },
  {
    imgURL: customer2,
    customerName: "User 1",
    rating: 4.5,
    feedback:
      "The product not only met but exceeded my expectations. I'll definitely be a returning customer!",
  },
];

export const footerLinks = [
  {
    title: "Products",
    links: [
      { name: "Air Force 1", link: "/" },
      { name: "Air Max 1", link: "/" },
      { name: "Air Jordan 1", link: "/" },
      { name: "Air Force 2", link: "/" },
      { name: "Nike Waffle Racer", link: "/" },
      { name: "Nike Cortez", link: "/" },
    ],
  },
  {
    title: "Help",
    links: [
      { name: "About us", link: "/" },
      { name: "FAQs", link: "/" },
      { name: "How it works", link: "/" },
      { name: "Privacy policy", link: "/" },
      { name: "Payment policy", link: "/" },
    ],
  },
  {
    title: "Get in touch",
    links: [
      { name: "customer@nike.com", link: "mailto:customer@nike.com" },
      { name: "+92554862354", link: "tel:+92554862354" },
    ],
  },
];

export const socialMedia = [
  { src: facebook, alt: "facebook logo" },
  { src: twitter, alt: "twitter logo" },
  { src: instagram, alt: "instagram logo" },
];
export const recommendedProducts = [
  {
    id: 1,
    name: "Chips & Dips",
    price: 150,
    imgURL: JD,
  },
  {
    id: 9,
    name: "Cheese Platter",
    price: 500,
    imgURL: redLabel,
  },
  {
    id: 10,
    name: "Cocktail Shaker Set",
    price: 1200,
    imgURL: jameson,
  },
  {
    id: 11,
    name: "Wine Glass Set",
    price: 800,
    imgURL: blackLabel,
  },
  {
    id: 5,
    name: "Barbecue Grill",
    price: 3000,
    imgURL: JD,
  },
  {
    id: 6,
    name: "Ice Bucket",
    price: 600,
    imgURL: redLabel,
  },
  {
    id: 7,
    name: "Mixed Nuts",
    price: 350,
    imgURL: jameson,
  },
  {
    id: 8,
    name: "Soft Drinks",
    price: 100,
    imgURL: blackLabel,
  },
];
export const categories = [
  {
    label: "Premium Collections",
    subcategories: [],
  },
  {
    label: "Spirits",
    subcategories: [
      "Whiskey",
      "Vodka",
      "Rum",
      "Gin",
      "Tequila",
      "Mezcal",
      "Cognac & Brandy",
      "Liqueurs",
    ],
  },
  {
    label: "Wines",
    subcategories: [
      "Red Wine",
      "White Wine",
      "Rose Wine",
      "Champagne & Sparkling Wine",
    ],
  },
  {
    label: "Beers, Infusions & Sake",
    subcategories: ["Beers", "Ciders", "Infusions", "Sake"],
  },
  {
    label: "Cocktails",
    subcategories: [],
  },
  {
    label: "Glassware",
    subcategories: [
      "Glassware",
      "Bar Accessories",
      "Cork Screws & Bottle Openers",
    ],
  },
  {
    label: "Non-Alcoholic Drinks",
    subcategories: [
      "Non-Alcoholic Wines",
      "Non-Alcoholic Beers",
      "Non-Alcoholic Spirits",
      "Soft Drinks & Mixers",
      "Mixers",
    ],
  },
  {
    label: "Smokes & Accessories",
    subcategories: ["Smoke Accessories", "Vapes"],
  },
  {
    label: "Others",
    subcategories: [],
  },
];
